efs/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('efs_app.urls')),
    url(r'^accounts/login/$', views.login, name='login'),
    url(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page': '/'}),

]

efs_app/urls.py
from django.conf.urls import url
from django.contrib import admin
from efs_app.views import IndexPage
from . import views
from rest_framework.urlpatterns import format_suffix_patterns

app_name = 'efs_app'

urlpatterns = [
    url(r'^$', IndexPage, name="home"),
    # url(r'^$', views.home, name='home'),
    # url(r'^home/$', views.home, name='home'),
    url(r'^customer/$', views.customer_list, name='customer_list'),
    url(r'^customer/(?P<pk>\d+)/delete/$', views.customer_delete, name='customer_delete'),
    url(r'^customer/(?P<pk>\d+)/edit/$', views.customer_edit, name='customer_edit'),
    url(r'^customer/(?P<pk>\d+)/portfolio/$', views.portfolio, name='portfolio'),
    url(r'^stock/$', views.stock_list, name='stock_list'),
    url(r'^stock/(?P<pk>\d+)/delete/$', views.stock_delete, name='stock_delete'),
    url(r'^stock/(?P<pk>\d+)/edit/$', views.stock_edit, name='stock_edit'),
    url(r'^stock/create/$', views.stock_new, name='stock_new'),
    url(r'^investment/$', views.investment_list, name='investment_list'),
    url(r'^investment/(?P<pk>\d+)/delete/$', views.investment_delete, name='investment_delete'),
    url(r'^investment/(?P<pk>\d+)/edit/$', views.investment_edit, name='investment_edit'),
    url(r'^investment/create/$', views.investment_new, name='investment_new'),
    url(r'^customers_json/', views.CustomerList.as_view(), name='customers_json'),
    url(r'^stocks_json/', views.StockList.as_view(), name='stocks_json'),
    url(r'^investments_json/', views.InvestmentList.as_view(), name='investments_json'),
    url(r'^(?P<pk>\d+)/investments_json/', views.InvestmentListAndStock.as_view(), name='investments_jsonpk'),
]
urlpatterns = format_suffix_patterns(urlpatterns)

efs_app/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
import requests

class Customer(models.Model):
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=200)
    cust_number = models.IntegerField(blank=False, null=False)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    zipcode = models.CharField(max_length=10)
    email = models.EmailField(max_length=200)
    cell_phone = models.CharField(max_length=50)
    created_date = models.DateTimeField(
        default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)


    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.cust_number)


class Investment(models.Model):
    customer = models.ForeignKey(Customer, related_name='investments')
    category = models.CharField(max_length=50)
    description = models.CharField(max_length=200)
    acquired_value = models.DecimalField(max_digits=10, decimal_places=2)
    acquired_date = models.DateField(default=timezone.now)
    recent_value = models.DecimalField(max_digits=10, decimal_places=2)
    recent_date = models.DateField(default=timezone.now, blank=True, null=True)

    def created(self):
        self.acquired_date = timezone.now()
        self.save()

    def updated(self):
        self.recent_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.customer)

    def results_by_investment(self):
        return self.recent_value - self.acquired_value

class Stock(models.Model):
    customer = models.ForeignKey(Customer, related_name='stocks')
    symbol = models.CharField(max_length=10)
    name = models.CharField(max_length=50)
    shares = models.DecimalField (max_digits=10, decimal_places=1)
    purchase_price = models.DecimalField(max_digits=10, decimal_places=2)
    purchase_date = models.DateField(default=timezone.now, blank=True, null=True)

    def created(self):
        self.recent_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.customer)

    def initial_stock_value(self):
        return self.shares * self.purchase_price

    def current_stock_price(self):
            symbol_f = str(self.symbol)
            main_api = 'https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol='
            api_key = '&interval=1min&apikey=UDI6E3XXJAC7VRM3'
            url = main_api + symbol_f + api_key
            json_data = requests.get(url).json()
            mkt_dt = (json_data["Meta Data"]["3. Last Refreshed"])
            open_price = float(json_data["Time Series (1min)"][mkt_dt]["1. open"])
            share_value = open_price
            return share_value

    def current_stock_value(self):
        symbol_f = str(self.symbol)
        main_api = 'https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol='
        api_key = '&interval=1min&apikey=UDI6E3XXJAC7VRM3'
        url = main_api + symbol_f + api_key
        json_data = requests.get(url).json()
        mkt_dt = (json_data["Meta Data"]["3. Last Refreshed"])
        open_price = float(json_data["Time Series (1min)"][mkt_dt]["1. open"])
        share_value = open_price
        return float(share_value) * float(self.shares)

efs_app/forms.py
from django import forms
from .models import Customer, Investment, Stock


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ('cust_number', 'name', 'address', 'city', 'state', 'zipcode', 'email', 'cell_phone',)


class InvestmentForm(forms.ModelForm):
    class Meta:
        model = Investment
        fields = (
            'customer', 'category', 'description', 'acquired_value', 'acquired_date', 'recent_value',
            'recent_date',)


class StockForm(forms.ModelForm):
    class Meta:
        model = Stock
        fields = ('customer', 'symbol', 'name', 'shares', 'purchase_price', 'purchase_date',)

efs_app/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.utils import timezone
from .models import *
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .forms import *
from django.db.models import Sum
from django.urls import reverse
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .serializers import CustomerSerializer, StockSerializer, InvestmentSerializer,CombinedSerializer



def IndexPage(request):
    template_name = "portfolio/index.html"
    return render(request, template_name)


def home(request):
   return render(request, 'portfolio/home.html',
                 {'portfolio': home})


@login_required
def customer_list(request):
   customer = Customer.objects.filter(created_date__lte=timezone.now())
   return render(request, 'portfolio/customer_list.html',
                 {'customers': customer})


@login_required
def customer_edit(request, pk):
   customer = get_object_or_404(Customer, pk=pk)
   if request.method == "POST":
       # update
       form = CustomerForm(request.POST, instance=customer)
       if form.is_valid():
           customer = form.save(commit=False)
           customer.updated_date = timezone.now()
           customer.save()
           customer = Customer.objects.filter(created_date__lte=timezone.now())
           return render(request, 'portfolio/customer_list.html',
                         {'customers': customer})
   else:
       # edit
       form = CustomerForm(instance=customer)
   return render(request, 'portfolio/customer_edit.html', {'form': form})


@login_required
def customer_delete(request, pk):
   customer = get_object_or_404(Customer, pk=pk)
   customer.delete()
   return redirect('efs_app:customer_list')


@login_required
def stock_list(request):
   stocks = Stock.objects.filter(purchase_date__lte=timezone.now())
   return render(request, 'portfolio/stock_list.html', {'stocks': stocks})


@login_required
def stock_new(request):
   if request.method == "POST":
       form = StockForm(request.POST)
       if form.is_valid():
           stock = form.save(commit=False)
           stock.created_date = timezone.now()
           stock.save()
           stocks = Stock.objects.filter(purchase_date__lte=timezone.now())
           return render(request, 'portfolio/stock_list.html',
                         {'stocks': stocks})
   else:
       form = StockForm()
       # print("Else")
   return render(request, 'portfolio/stock_new.html', {'form': form})


@login_required
def stock_edit(request, pk):
   stock = get_object_or_404(Stock, pk=pk)
   if request.method == "POST":
       form = StockForm(request.POST, instance=stock)
       if form.is_valid():
           stock = form.save()
           # stock.customer = stock.id
           stock.updated_date = timezone.now()
           stock.save()
           stocks = Stock.objects.filter(purchase_date__lte=timezone.now())
           return render(request, 'portfolio/stock_list.html', {'stocks': stocks})
   else:
       # print("else")
       form = StockForm(instance=stock)
   return render(request, 'portfolio/stock_edit.html', {'form': form})


@login_required
def stock_delete(request, pk):
   stock = get_object_or_404(Stock, pk=pk)
   stock.delete()
   stocks = Stock.objects.filter(purchase_date__lte=timezone.now())
   return render(request, 'portfolio/stock_list.html', {'stocks': stocks})


@login_required
def investment_list(request):
   investments = Investment.objects.filter(acquired_date__lte=timezone.now())
   return render(request, 'portfolio/investment_list.html', {'investments': investments})

@login_required
def investment_new(request):
   if request.method == "POST":
       form = InvestmentForm(request.POST)
       if form.is_valid():
           investment = form.save(commit=False)
           investment.created_date = timezone.now()
           investment.save()
           investments = Investment.objects.filter(acquired_date__lte=timezone.now())
           return render(request, 'portfolio/investment_list.html',
                         {'investments': investments})
   else:
       form = InvestmentForm()
       # print("Else")
   return render(request, 'portfolio/investment_new.html', {'form': form})


@login_required
def investment_edit(request, pk):
   investment = get_object_or_404(Investment, pk=pk)
   if request.method == "POST":
       form = InvestmentForm(request.POST, instance=investment)
       if form.is_valid():
           investment = form.save()
           # stock.customer = stock.id
           investment.updated_date = timezone.now()
           investment.save()
           investments = Investment.objects.filter(acquired_date__lte=timezone.now())
           return render(request, 'portfolio/investment_list.html', {'investments': investments})
   else:
       # print("else")
       form = InvestmentForm(instance=investment)
   return render(request, 'portfolio/investment_edit.html', {'form': form})


@login_required
def investment_delete(request, pk):
   investment = get_object_or_404(Investment, pk=pk)
   investment.delete()
   investments = Investment.objects.filter(acquired_date__lte=timezone.now())
   return render(request, 'portfolio/investment_list.html', {'investments': investments})

@login_required
def portfolio(request, pk):
    customer = get_object_or_404(Customer, pk=pk)
    customers = Customer.objects.filter(created_date__lte=timezone.now())
    investments = Investment.objects.filter(customer=pk)
    stocks = Stock.objects.filter(customer=pk)
    sum_acquired_value = Investment.objects.filter(customer=pk).aggregate(Sum('acquired_value'))
    sum_recent_value = Investment.objects.filter(customer=pk).aggregate(Sum('recent_value'))
    sav = float(sum_acquired_value['acquired_value__sum'])
    srv = float(sum_recent_value['recent_value__sum'])
    print (sav)
    print (srv)
    # Initialize the value of the stocks
    sum_current_stocks_value = 0
    sum_of_initial_stock_value = 0

    # Loop through each stock and add the value to the total
    for stock in stocks:
        sum_current_stocks_value += stock.current_stock_value()
        sum_of_initial_stock_value += stock.initial_stock_value()

    return render(request, 'portfolio/portfolio.html', {'customers': customers, 'investments': investments,
                                                        'stocks': stocks,
                                                        'sum_acquired_value': sum_acquired_value,
                                                        'sum_recent_value': sum_recent_value,
                                                        'sum_current_stocks_value': sum_current_stocks_value,
                                                        'sum_of_initial_stock_value': sum_of_initial_stock_value,
                                                        'sav':sav,
                                                        'srv':srv,
                                                        'stockdiff': float(sum_current_stocks_value) - float(sum_of_initial_stock_value),
                                                        'acquirediff': float(srv) - float(sav) })


# List at the end of the views.py
# Lists all customers 
class CustomerList(APIView):

    def get(self,request):
        customers_json = Customer.objects.all()
        serializer = CustomerSerializer(customers_json, many=True)
        return Response(serializer.data)

# List at the end of the views.py
# Lists all Stock 
class StockList(APIView):
    
    def get(self,request):
        stocks_json = Stock.objects.all()
        serializer = StockSerializer(stocks_json, many=True)
        return Response(serializer.data)

# List at the end of the views.py
# Lists all investment 
class InvestmentList(APIView):
    
    def get(self,request):
        investments_json = Investment.objects.all()
        serializer = InvestmentSerializer(investments_json, many=True)
        return Response(serializer.data)

from collections import namedtuple
class InvestmentListAndStock(APIView):
    
    def get(self,request, pk):
        Timeline = namedtuple('Timeline', ('investment', 'stock'))
        timeline = Timeline(
        investment = Investment.objects.filter(customer_id=pk),
        stock = Stock.objects.filter(customer_id=pk),
        )
        # serializerstk = StockSerializer(stocks_json, many=True)
        # serializerinvt = InvestmentSerializer(investments_json, many=True)
        # combined = (investments_json, stocks_json)
        serializer = CombinedSerializer(timeline)
        return Response(serializer.data)

efs_app/templates/portfolio/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Eagle Financial Services</title>

    <!-- Bootstrap core CSS -->
    {% comment %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css"> {% endcomment %}

    <link href="https://blackrockdigital.github.io/startbootstrap-3-col-portfolio/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="https://blackrockdigital.github.io/startbootstrap-3-col-portfolio/css/3-col-portfolio.css" rel="stylesheet">

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="/">Eagle Financial Services</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="/">Home
                <span class="sr-only">(current)</span>
              </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'efs_app:customer_list' %}">Customers</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'efs_app:investment_list' %}">Investments</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'efs_app:stock_list' %}">Stocks</a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            <span class="badge">{{user.username}}<span class="caret"></span></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{% url 'logout' %}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                        </ul>
                    </li>
                    {% else %}
                    <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>

    <!-- Page Content -->
    <div class="container">
        {% block content %} {% endblock content %}
    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Eagle Financial Services 2018</p>
        </div>
        <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="https://blackrockdigital.github.io/startbootstrap-3-col-portfolio/vendor/jquery/jquery.min.js"></script>
    <script src="https://blackrockdigital.github.io/startbootstrap-3-col-portfolio/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>

</html>

efs_app/templates/portfolio/customer_delete.html
{% extends "portfolio/base.html" %} {% block body_block %}
<h1>Delete {{ customer.name }}?</h1>

<form method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Delete">
    <a href="{% url ''efs_app:home' pk=customer.cust_number %} ">Cancel</a>

</form>

{% endblock %}

efs_app/templates/portfolio/customer_edit.html
{% extends 'portfolio/base.html' %}

{% block content %}
    <h1>Edit Customer</h1>
    <form method="POST" class="customer-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Update</button>
    </form>
{% endblock %}

efs_app/templates/portfolio/customer_list.html
{% extends 'portfolio/base.html' %} {% block content %}

<body>
    <style>
        body {
            background-color: beige;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-default">
                    <h3 class="panel-heading">Welcome!</h3>
                    <p class="panel-body">
                        Eagle Financial Services, your Midwest Financial Services Partner.
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <h2 style="padding-left: 15Px">Customer Information</h2>
    </div>
    <div>
        <table class="table table-striped table-bordered table-hover table-responsive">
            <thead>
                <tr class="bg-info">
                    <th>Customer Number</th>
                    <th>Name</th>
                    <th>Address</th>
                    <th>City</th>
                    <th>State</th>
                    <th>Zip</th>
                    <th>Primary Email</th>
                    <th>Cell Phone</th>
                    <th colspan="3">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for customer in customers %}
                <tr>
                    <td>{{ customer.cust_number }}</td>
                    <td>{{ customer.name }}</td>
                    <td>{{ customer.address }}</td>
                    <td>{{ customer.city }}</td>
                    <td>{{ customer.state }}</td>
                    <td>{{ customer.zipcode }}</td>
                    <td>{{ customer.email }}</td>
                    <td>{{ customer.cell_phone }}</td>
                    <td><a href="{% url 'efs_app:customer_edit' pk=customer.pk %}" class="btn btn-warning">Edit</a>
                        <td><a href="{% url 'efs_app:customer_delete' pk=customer.pk %}" onclick="return confirm('Are you sure you want to delete?')" class="btn btn-danger">Delete</a>
                        </td>
                        <td><a href="{% url 'efs_app:portfolio' pk=customer.pk %}" class="btn btn-primary">Portfolio</a>
                        </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% comment %} {#
        <div class="row">#} {#
            <a href="{% url 'customer_new' %}" class="row">
                <span#} {# class="btn btn-primary">Add Customer</span>
            </a>#} {# </div>#} {% endcomment %}
    </div>
</body>

</html>
{% endblock %}

efs_app/templates/portfolio/customer_new.html
{% extends 'portfolio/customer.html' %}

{% block content %}
    <h1>Add a New Customer</h1>
     <form method="POST" class="customer-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

efs_app/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}
{% load staticfiles %}
{% block content %}
            {% if user.is_authenticated %}
                <div class="page-container">

                    <h2 class="top-menu">Hello {{ user.username }},</h2>
                    <p>Please choose from below options.</p>

                </div>
            {% endif %}
            <div class="content container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="links">
                            <!-- Example row of columns -->
                            <div class="row">
                                <div class="col-md-3">
                                    <div class="thumbnail">
                                        <img src="{% static "images/customer.jpg" %}" alt="customer"/>
                                        <div class="caption">
                                            <h2>Customer</h2>
                                            <p>We see our success in our customers success, it gives us an immense
                                                pleasure when our
                                                advises
                                                turn out to be fruitful. </p>
                                            <p><a class="btn btn-primary" href="{% url 'portfolio:customer_list' %}"
                                                  role="button">View
                                                details &raquo;</a></p>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="thumbnail">
                                        <img src="{% static "images/nonstock.jpg" %}" alt="non-stock"/>
                                        <div class="caption">
                                            <h2>Non-Stock Investments</h2>
                                            <p>Our team also provides advises for Non-Stock investments.</p>
                                            <p><a class="btn btn-primary" href="{% url 'portfolio:investment_list' %}"
                                                  role="button">View
                                                details &raquo;</a></p>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="thumbnail">
                                        <img src="{% static "images/stocks.jpg" %}" alt="stocks"/>
                                        <div class="caption">
                                            <h2>Stock Portfolio</h2>
                                            <p>Our Stock portfolios vary across industries.</p>
                                            <p><a class="btn btn-primary" href="{% url 'portfolio:stock_list' %}"
                                                  role="button">View
                                                details &raquo;</a></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </body>
    </html>
{% endblock %}

efs_app/templates/portfolio/index.html
{% extends "base.html" %} {% block content %}
<!-- Page Heading -->
<h3 class="my-4">Hi Lorem!<br/>
    <small>Choose from below your preffered service</small>
</h3>

<div class="row">
    <div class="col-lg-4 col-sm-6 portfolio-item">
        <div class="card h-100">
            <a href="#"><img class="card-img-top" src="https://onlinemastery.co.uk/wp-content/uploads/2016/02/avatar-1.jpg" alt=""></a>
            <div class="card-body">
                <h4 class="card-title">
                    Customer
                </h4>
                <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
                <div> {% if user.is_authenticated %}
                    <a class="btn btn-primary btn-block" href="{% url 'efs_app:customer_list' %}" role="button">View
                            details &raquo;</a> {% endif %}</div>
            </div>
        </div>
    </div>
    <div class="col-lg-4 col-sm-6 portfolio-item">
        <div class="card h-100">
            <a href="#"><img class="card-img-top" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTx_VfYWU2bTMNBmhSSz2jQ2PyCa77JGvl50a1M8eT-KDpMeIK43Q" alt=""></a>
            <div class="card-body">
                <h4 class="card-title">
                    Investment
                </h4>
                <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
                <div> {% if user.is_authenticated %}
                    <a class="btn btn-primary btn-block" href="{% url 'efs_app:investment_list' %}" role="button">View
                            details &raquo;</a> {% endif %}</div>
            </div>
        </div>
    </div>
    <div class="col-lg-4 col-sm-6 portfolio-item">
        <div class="card h-100">
            <a href="#"><img class="card-img-top" src="https://fm.cnbc.com/applications/cnbc.com/resources/img/editorial/2012/11/09/100110256-stocks_portfolio.530x298.jpg?v=1363716376" alt=""></a>
            <div class="card-body">
                <h4 class="card-title">
                    Stocks Portfolio
                </h4>
                <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
                <div> {% if user.is_authenticated %}
                    <a class="btn btn-primary btn-block" href="{% url 'efs_app:stock_list' %}" role="button">View
                            details &raquo;</a> {% endif %}</div>
            </div>
        </div>
    </div>
    <!-- <div class="col-lg-4 col-sm-6 portfolio-item">
        <div class="card h-100">
            <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
            <div class="card-body">
                <h4 class="card-title">
                    <a href="#">Project Four</a>
                </h4>
                <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
            </div>
        </div>
    </div>
    <div class="col-lg-4 col-sm-6 portfolio-item">
        <div class="card h-100">
            <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
            <div class="card-body">
                <h4 class="card-title">
                    <a href="#">Project Five</a>
                </h4>
                <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
            </div>
        </div>
    </div>
    <div class="col-lg-4 col-sm-6 portfolio-item">
        <div class="card h-100">
            <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
            <div class="card-body">
                <h4 class="card-title">
                    <a href="#">Project Six</a>
                </h4>
                <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque earum nostrum suscipit ducimus nihil provident, perferendis rem illo, voluptate atque, sit eius in voluptates, nemo repellat fugiat excepturi! Nemo, esse.</p>
            </div>
        </div>
    </div> -->
</div>
<!-- /.row -->

<!-- Pagination -->
<!-- <ul class="pagination justify-content-center">
    <li class="page-item">
        <a class="page-link" href="#" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
        </a>
    </li>
    <li class="page-item">
        <a class="page-link" href="#">1</a>
    </li>
    <li class="page-item">
        <a class="page-link" href="#">2</a>
    </li>
    <li class="page-item">
        <a class="page-link" href="#">3</a>
    </li>
    <li class="page-item">
        <a class="page-link" href="#" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
        </a>
    </li>
</ul> -->
{% endblock %}

efs_app/templates/portfolio/investment_delete.html
{% extends "portfolio/base.html" %} {% block body_block %}
<h1>Delete {{ customer.name }}?</h1>
<h1>Delete {{ investment.category }}?</h1>
<form method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Delete">
    <a href="{% url 'efs_app:home' pk=investment.cust_number %} ">Cancel</a>

</form>

{% endblock %}

efs_app/templates/portfolio/investment_edit.html
{% extends 'portfolio/base.html' %} {% block content %}
<h1>Edit Investment</h1>
<form method="POST" class="stock-form">{% csrf_token %} {{ form.as_p }}
    <button type="submit" class="save btn btn-default">Update</button>
</form>
<br/> {% endblock %}